---
title: "Clean QP on the Linux Server"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{my-vignette}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  eval = FALSE 
)
```

```{r setup}
#library(QPcleaneR)

library(furrr)
library(data.table)

# Choose the number of cores for parallel processing
n_cores <- 20
```


```{r}
#set the paralel for furrr
furrr::plan(multisession, 
            workers = n_cores)
```


This lines create a fuction that is both 

```{r}
# a raw dataset that has establishment, worker and firm level info.
# for all years in the indicated directories.
df <- qp_assemble(path_worker_dir = "../1_raw_data/010_workers",
                  path_firm_dir = "../1_raw_data/020_firms",
                  path_est_fir = "../1_raw_data/030_establishment")
```


Save the RAW complete data.

```{r}
df_raw %>% data.table::fwrite("../2_data/030_final_versions/df_raw_qp.csv")
```


# Delete Worker Duplicates

```{r}
df %<>% delete_worker_duplicates(type = "highest")
```


# The crosswalks: make it consisntes

Load the raw dataset:

```{r}
df <- data.table::fread("../2_data/030_final_versions/df_raw_qp.csv") %>% as_tibble()
```


```{r}
df %<>% qp_crosswalks()
```

This function changes:
1. worker, delete NAs and put all NA's in 1985;
1. cae_3;
1. year founded;
1. nut_2_firm;
1. nut_2_est;
1. firm;
1. occupation;
1. Sector;
1. Education;
10; Establishment;



# save

```{r}
df %>% saveRDS("../2_data/030_final_versions/qp+crosswalks.rds")
```


# Clean








